### ISSUE TITLE
Website QA

### ISSUE THREAD

**Issue by lukefretwell** [proudlyserving/proudlyserving.github.io#47]
* Test forms
* Review pages for content consistency
* Check all links
* Subscribe / follow socials https://proudlyservingbook.com/updates/

- [x] @rebeccawoodbury 
- [x] @lukefretwell

**Comment by rebeccawoodbury** [comment]
@lukefretwell 

- the link on this page goes to the same page https://proudlyservingbook.com/license, is that on purpose? should we add a link to "Creative Commons" so people who aren't familiar can learn about it?
- consider deleting "Write about an existing theme or suggest a new one." on https://proudlyservingbook.com/contribute/
- third paragraph on https://proudlyservingbook.com/conduct/, should "Definitions" be a heading for the next section? same with "Consequences" in paragraph third from bottom?
- also re code of conduct - should we just reference "maintainers" instead of calling us the anti-abuse team?
- did we get the code of conduct from somewhere else? should we say that?
- should this page be added to the footer? https://proudlyservingbook.com/collaborate
- should the bullets in "General" have periods at the end of them?

**Comment by lukefretwell** [comment]
@rebeccawoodbury comments:

> the link on this page goes to the same page https://proudlyservingbook.com/license, is that on purpose? should we add a link to "Creative Commons" so people who aren't familiar can learn about it?

Done.

> consider deleting "Write about an existing theme or suggest a new one." on https://proudlyservingbook.com/contribute/

Think it would be good to have an open option, as I imagine there will be some interesting themes we're not thinking about.

> third paragraph on https://proudlyservingbook.com/conduct/, should "Definitions" be a heading for the next section? same with "Consequences" in paragraph third from bottom?

I updated the entire code of conduct with the latest version and added maintainer and email, but if you could review and edit as you see fit, that would be great.

> also re code of conduct - should we just reference "maintainers" instead of calling us the anti-abuse team?

Done.

> did we get the code of conduct from somewhere else? should we say that?

Done.

> should this page be added to the footer? https://proudlyservingbook.com/collaborate

Done. Created a new footer menu for that.

> should the bullets in "General" have periods at the end of them?

Done.
